describe('Selecting an account after logging in SCENARIO A ', function(){
    beforeEach(function(){
        cy.visit('https://app.perkbox.com')
        cy.contains('Please sign in with your email')
        cy.url()
          .should('include', '/welcome/login')
        cy.get('input[name=email]')
          .type('pooja@perkbox.co.uk')
          .should('have.value', 'pooja@perkbox.co.uk')
    })

    it('should display prepopulated field once account is selected and we click on CONFIRM', function(){
          cy.get('button')
            .children()
            .last()
            .click()
          cy.contains('demo-test-france')
            .click()
          cy.get('button')
            .children()
            .last()
            .click()
          cy.url()
            .should('include', 'demo-test-france')
          cy.get('input[name=email]') 
            .should('have.value', 'pooja@perkbox.co.uk')
    })
})

describe('Cannot log in, no account found : SCENARIO B ', function(){
    it('should display an error message if email does not belong to an account', function(){
        cy.visit('https://app.perkbox.com')
        cy.contains('Please sign in with your email')
        cy.url()
          .should('include', '/welcome/login')
        cy.get('input[name=email]')
          .type('noaccount@fake.co.uk')
          .should('have.value', 'noaccount@fake.co.uk')
        cy.get('button')
          .children()
          .last()
          .click()
        cy.contains("User is not found")
    })
})